name: Kernel Code Release

on:
  push:
  pull_request:
  schedule:
    - cron: "05 9 * * *" # every day at 09:05AM

jobs:
  check:
    name: Kernel Code Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add x86_64-unknown-none
      - run: cargo check --target x86_64-unknown-none

  test:
    name: Kernel Code Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add x86_64-unknown-none
      - run: cargo build --target x86_64-unknown-none

  fmt:
    name: Kernel Code Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all -- --check

  clippy:
    name: Kernel Code Clippy Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add x86_64-unknown-none
      - run: rustup component add clippy
      - run: cargo clippy --target x86_64-unknown-none
